//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADORAS_CARTAO
    {
        public ADMINISTRADORAS_CARTAO()
        {
            this.LOJA_VENDA_PARCELAS = new HashSet<LOJA_VENDA_PARCELAS>();
        }
    
        public string CODIGO_ADMINISTRADORA { get; set; }
        public string ADMINISTRADORA { get; set; }
        public Nullable<decimal> TAXA_ADMINISTRACAO { get; set; }
        public Nullable<int> DIA_ACERTO { get; set; }
        public string CARTAO_TELEFONE { get; set; }
        public string CARTAO_NOSSO_NUM { get; set; }
        public string CARTAO_TEL_VOZ { get; set; }
        public int CARTAO_PRE_PARCELAS { get; set; }
        public bool ACEITA_PARCELAMENTO { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public Nullable<short> PARCELAS_JUROS_LOJA { get; set; }
        public Nullable<short> TIPO_CARTAO { get; set; }
        public Nullable<int> DIAS_ENTRE_PARCELAS { get; set; }
        public Nullable<short> PARCELAS_MES_FECHADO { get; set; }
        public Nullable<short> SUGESTAO_PARCELAMENTO { get; set; }
        public string REDE_CONTROLADORA { get; set; }
        public string LX_COD_ADMINISTRADORA { get; set; }
        public bool INATIVO { get; set; }
    
        public virtual ICollection<LOJA_VENDA_PARCELAS> LOJA_VENDA_PARCELAS { get; set; }
    }
}
