//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSS_PARAMETRO_VENDEDOR
    {
        public string vendedor { get; set; }
        public decimal comisionCumple { get; set; }
        public decimal comisionNoCumple { get; set; }
    }
}
