//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOJAS_REDE
    {
        public LOJAS_REDE()
        {
            this.PRODUTOS = new HashSet<PRODUTOS>();
        }
    
        public string REDE_LOJAS { get; set; }
        public string DESC_REDE_LOJAS { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public string REDE_SIGLA { get; set; }
    
        public virtual ICollection<PRODUTOS> PRODUTOS { get; set; }
    }
}
