//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOJA_VENDEDORES
    {
        public LOJA_VENDEDORES()
        {
            this.LOJA_VENDA_PGTO = new HashSet<LOJA_VENDA_PGTO>();
        }
    
        public string VENDEDOR { get; set; }
        public string CODIGO_FILIAL { get; set; }
        public string VENDEDOR_APELIDO { get; set; }
        public string NOME_VENDEDOR { get; set; }
        public bool OPERA_CAIXA { get; set; }
        public Nullable<decimal> COMISSAO { get; set; }
        public string RG { get; set; }
        public string ENDERECO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public string TELEFONE { get; set; }
        public string CPF { get; set; }
        public string GERENTE { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public string SENHA { get; set; }
        public Nullable<System.DateTime> DATA_DESATIVACAO { get; set; }
        public Nullable<System.DateTime> DATA_ATIVACAO { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public string DESC_CARGO { get; set; }
        public bool ACESSO_GERENCIAL { get; set; }
        public string CHECKSUM { get; set; }
        public string VENDEDOR_FRANQUIA { get; set; }
        public Nullable<decimal> COMISSAO_CLIENTE_AUSENTE { get; set; }
    
        public virtual ICollection<LOJA_VENDA_PGTO> LOJA_VENDA_PGTO { get; set; }
    }
}
