//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOJA_VENDA_PARCELAS
    {
        public string TERMINAL { get; set; }
        public string LANCAMENTO_CAIXA { get; set; }
        public string CODIGO_FILIAL { get; set; }
        public string PARCELA { get; set; }
        public string CODIGO_ADMINISTRADORA { get; set; }
        public string TIPO_PGTO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<System.DateTime> VENCIMENTO { get; set; }
        public string NUMERO_TITULO { get; set; }
        public string MOEDA { get; set; }
        public string AGENCIA { get; set; }
        public string BANCO { get; set; }
        public string CONTA_CORRENTE { get; set; }
        public string NUMERO_APROVACAO_CARTAO { get; set; }
        public int PARCELAS_CARTAO { get; set; }
        public Nullable<decimal> VALOR_CANCELADO { get; set; }
        public string CHEQUE_CARTAO { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public string NUMERO_LOTE { get; set; }
        public string FINALIZACAO { get; set; }
        public Nullable<short> BAIXA { get; set; }
        public string REDE_CONTROLADORA { get; set; }
        public Nullable<decimal> COTACAO { get; set; }
        public Nullable<decimal> VALOR_MOEDA { get; set; }
        public Nullable<byte> ORIGEM_LOTE { get; set; }
        public Nullable<decimal> TROCO { get; set; }
        public Nullable<System.DateTime> DATA_HORA_TEF { get; set; }
        public string CHEQUE_DIGITO { get; set; }
        public Nullable<int> ID_DOCUMENTO_ECF { get; set; }
    
        public virtual ADMINISTRADORAS_CARTAO ADMINISTRADORAS_CARTAO { get; set; }
        public virtual LOJA_VENDA_PGTO LOJA_VENDA_PGTO { get; set; }
        public virtual TIPOS_PGTO TIPOS_PGTO { get; set; }
    }
}
