//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOJA_VENDA_PRODUTO
    {
        public string TICKET { get; set; }
        public string CODIGO_FILIAL { get; set; }
        public System.DateTime DATA_VENDA { get; set; }
        public string ITEM { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string PRODUTO { get; set; }
        public string COR_PRODUTO { get; set; }
        public Nullable<short> TAMANHO { get; set; }
        public Nullable<int> QTDE { get; set; }
        public Nullable<decimal> PRECO_LIQUIDO { get; set; }
        public Nullable<decimal> DESCONTO_ITEM { get; set; }
        public string NUMERO_IMP_FISCAL { get; set; }
        public Nullable<int> QTDE_CANCELADA { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public Nullable<decimal> CUSTO { get; set; }
        public Nullable<decimal> FATOR_DESCONTO_VENDA { get; set; }
        public Nullable<decimal> FATOR_VENDA_LIQ { get; set; }
        public Nullable<decimal> IPI { get; set; }
        public Nullable<decimal> ALIQUOTA { get; set; }
        public Nullable<short> ID_VENDEDOR { get; set; }
        public bool ITEM_EXCLUIDO { get; set; }
        public byte QTDE_BRINDE { get; set; }
    }
}
