//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOJA_FORMAS_PGTO
    {
        public LOJA_FORMAS_PGTO()
        {
            this.LOJA_VENDA_PGTO = new HashSet<LOJA_VENDA_PGTO>();
        }
    
        public string COD_FORMA_PGTO { get; set; }
        public string FORMA_PGTO { get; set; }
        public Nullable<System.DateTime> DATA_CRIACAO { get; set; }
        public bool PERMITE_ALTERAR { get; set; }
        public Nullable<System.DateTime> ATIVAR_EM { get; set; }
        public Nullable<System.DateTime> DESATIVAR_EM { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<decimal> VALOR_MINIMO { get; set; }
        public Nullable<decimal> VALOR_MAXIMO { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public Nullable<System.DateTime> VENC_RELATIVO { get; set; }
        public int DESCONTO_POR_ITEM { get; set; }
        public Nullable<short> PARCELAS_CARTAO_INICIAL { get; set; }
    
        public virtual ICollection<LOJA_VENDA_PGTO> LOJA_VENDA_PGTO { get; set; }
    }
}
