//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOJA_VENDA_PGTO
    {
        public LOJA_VENDA_PGTO()
        {
            this.LOJA_VENDA_PARCELAS = new HashSet<LOJA_VENDA_PARCELAS>();
        }
    
        public string CODIGO_FILIAL { get; set; }
        public string TERMINAL { get; set; }
        public string LANCAMENTO_CAIXA { get; set; }
        public string COD_FORMA_PGTO { get; set; }
        public string CAIXA_VENDEDOR { get; set; }
        public Nullable<System.DateTime> DIGITACAO { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string NUMERO_CUPOM_FISCAL { get; set; }
        public Nullable<decimal> DESCONTO_PGTO { get; set; }
        public Nullable<decimal> TOTAL_VENDA { get; set; }
        public Nullable<decimal> VALOR_CANCELADO { get; set; }
        public string PERIODO_FECHAMENTO { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public string SERIE_NF_ENTRADA { get; set; }
        public string SERIE_NF_SAIDA { get; set; }
        public Nullable<decimal> FATOR { get; set; }
        public string NUMERO_FISCAL_TROCA { get; set; }
        public Nullable<short> CANCELADO_FISCAL { get; set; }
        public string ID_EQUIPAMENTO { get; set; }
        public Nullable<short> IMPRIMIU_CUPOM_TROCA { get; set; }
        public bool VENDA_FINALIZADA { get; set; }
        public string NUMERO_FISCAL_CANCELAMENTO { get; set; }
        public string NUMERO_FATURA_MANUAL { get; set; }
        public string SERIE_NF_CANCELAMENTO { get; set; }
        public string NUMERO_FISCAL_VENDA { get; set; }
        public string SERIE_NF { get; set; }
        public Nullable<int> NUMERO_CCF { get; set; }
        public Nullable<int> ID_DOCUMENTO_ECF_TROCA { get; set; }
        public Nullable<int> ID_DOCUMENTO_ECF_VALE { get; set; }
    
        public virtual LOJA_FORMAS_PGTO LOJA_FORMAS_PGTO { get; set; }
        public virtual ICollection<LOJA_VENDA_PARCELAS> LOJA_VENDA_PARCELAS { get; set; }
        public virtual LOJA_VENDEDORES LOJA_VENDEDORES { get; set; }
    }
}
