//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTOS
    {
        public string PRODUTO { get; set; }
        public string CODIGO_PRECO { get; set; }
        public string MATERIAL { get; set; }
        public string PERIODO_PCP { get; set; }
        public string TABELA_OPERACOES { get; set; }
        public Nullable<decimal> FATOR_OPERACOES { get; set; }
        public string CLASSIF_FISCAL { get; set; }
        public string TIPO_PRODUTO { get; set; }
        public string TABELA_MEDIDAS { get; set; }
        public string DESC_PRODUTO { get; set; }
        public string GRUPO_PRODUTO { get; set; }
        public string SUBGRUPO_PRODUTO { get; set; }
        public string COLECAO { get; set; }
        public string GRADE { get; set; }
        public string DESC_PROD_NF { get; set; }
        public string LINHA { get; set; }
        public string GRIFFE { get; set; }
        public string CARTELA { get; set; }
        public string UNIDADE { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public bool REVENDA { get; set; }
        public string REFER_FABRICANTE { get; set; }
        public string MODELAGEM { get; set; }
        public bool SORTIMENTO_COR { get; set; }
        public string FABRICANTE { get; set; }
        public bool SORTIMENTO_TAMANHO { get; set; }
        public bool VARIA_PRECO_COR { get; set; }
        public bool VARIA_PRECO_TAM { get; set; }
        public string PONTEIRO_PRECO_TAM { get; set; }
        public bool VARIA_CUSTO_COR { get; set; }
        public bool PERTENCE_A_CONJUNTO { get; set; }
        public string TRIBUT_ICMS { get; set; }
        public string TRIBUT_ORIGEM { get; set; }
        public bool VARIA_CUSTO_TAM { get; set; }
        public Nullable<decimal> CUSTO_REPOSICAO1 { get; set; }
        public Nullable<decimal> CUSTO_REPOSICAO2 { get; set; }
        public Nullable<decimal> CUSTO_REPOSICAO3 { get; set; }
        public Nullable<decimal> CUSTO_REPOSICAO4 { get; set; }
        public Nullable<System.DateTime> DATA_REPOSICAO { get; set; }
        public string ESTILISTA { get; set; }
        public string MODELISTA { get; set; }
        public Nullable<int> TAMANHO_BASE { get; set; }
        public Nullable<int> GIRO_ENTREGA { get; set; }
        public byte[] TIMESTAMP { get; set; }
        public bool INATIVO { get; set; }
        public bool ENVIA_LOJA_VAREJO { get; set; }
        public bool ENVIA_LOJA_ATACADO { get; set; }
        public bool ENVIA_REPRESENTANTE { get; set; }
        public bool ENVIA_VAREJO_INTERNET { get; set; }
        public bool ENVIA_ATACADO_INTERNET { get; set; }
        public string MODELO { get; set; }
        public string REDE_LOJAS { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public Nullable<decimal> FABRICANTE_ICMS_ABATER { get; set; }
        public Nullable<int> FABRICANTE_PRAZO_PGTO { get; set; }
        public Nullable<decimal> TAXA_JUROS_DEFLACIONAR { get; set; }
        public Nullable<decimal> TAXAS_IMPOSTOS_APLICAR { get; set; }
        public Nullable<decimal> PRECO_REPOSICAO_1 { get; set; }
        public Nullable<decimal> PRECO_REPOSICAO_2 { get; set; }
        public Nullable<decimal> PRECO_REPOSICAO_3 { get; set; }
        public Nullable<decimal> PRECO_REPOSICAO_4 { get; set; }
        public Nullable<decimal> PRECO_A_VISTA_REPOSICAO_1 { get; set; }
        public Nullable<decimal> PRECO_A_VISTA_REPOSICAO_2 { get; set; }
        public Nullable<decimal> PRECO_A_VISTA_REPOSICAO_3 { get; set; }
        public Nullable<decimal> PRECO_A_VISTA_REPOSICAO_4 { get; set; }
        public Nullable<decimal> FABRICANTE_FRETE { get; set; }
        public Nullable<short> DROP_DE_TAMANHOS { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRAMENTO { get; set; }
        public string STATUS_PRODUTO { get; set; }
        public Nullable<int> TIPO_STATUS_PRODUTO { get; set; }
        public string OBS { get; set; }
        public string COMPOSICAO { get; set; }
        public string RESTRICAO_LAVAGEM { get; set; }
        public int EMPRESA { get; set; }
        public string ORCAMENTO { get; set; }
        public string CLIENTE_DO_PRODUTO { get; set; }
        public string CONTA_CONTABIL { get; set; }
        public Nullable<decimal> ESPESSURA { get; set; }
        public Nullable<decimal> ALTURA { get; set; }
        public Nullable<decimal> LARGURA { get; set; }
        public Nullable<decimal> COMPRIMENTO { get; set; }
        public Nullable<short> EMPILHAMENTO_MAXIMO { get; set; }
        public Nullable<short> SEXO_TIPO { get; set; }
        public Nullable<short> PARTE_TIPO { get; set; }
        public string VERSAO_FICHA { get; set; }
        public string COD_FLUXO_PRODUTO { get; set; }
        public Nullable<System.DateTime> DATA_INICIO_DESENVOLVIMENTO { get; set; }
        public Nullable<byte> INDICADOR_CFOP { get; set; }
        public Nullable<byte> MONTAGEM_KIT { get; set; }
        public Nullable<int> MRP_AGRUPAR_NECESSIDADE_DIAS { get; set; }
        public Nullable<int> MRP_AGRUPAR_NECESSIDADE_TIPO { get; set; }
        public Nullable<int> MRP_DIAS_SEGURANCA { get; set; }
        public Nullable<int> MRP_EMISSAO_LIBERACAO_DIAS { get; set; }
        public Nullable<int> MRP_ENTREGA_GIRO_DIAS { get; set; }
        public Nullable<int> MRP_PARTICIPANTE { get; set; }
        public Nullable<int> MRP_MAIOR_GIRO_MP_DIAS { get; set; }
        public Nullable<int> MRP_FP { get; set; }
        public Nullable<int> MRP_RR { get; set; }
        public bool OP_POR_COR { get; set; }
        public Nullable<int> OP_QTDE_MAXIMA { get; set; }
        public Nullable<int> OP_QTDE_MINIMA { get; set; }
        public Nullable<byte> QUALIDADE { get; set; }
        public Nullable<int> SEMI_ACABADO { get; set; }
        public string CONTA_CONTABIL_COMPRA { get; set; }
        public string CONTA_CONTABIL_VENDA { get; set; }
        public string CONTA_CONTABIL_DEV_COMPRA { get; set; }
        public string CONTA_CONTABIL_DEV_VENDA { get; set; }
        public Nullable<int> ID_EXCECAO_GRUPO { get; set; }
        public Nullable<int> ID_EXCECAO_IMPOSTO { get; set; }
        public string DIAS_COMPRA { get; set; }
        public Nullable<byte> FATOR_P { get; set; }
        public Nullable<byte> FATOR_Q { get; set; }
        public Nullable<byte> FATOR_F { get; set; }
        public Nullable<byte> CONTINUIDADE { get; set; }
        public string COD_CATEGORIA { get; set; }
        public string COD_SUBCATEGORIA { get; set; }
        public Nullable<int> COD_PRODUTO_SOLUCAO { get; set; }
        public Nullable<int> COD_PRODUTO_SEGMENTO { get; set; }
    
        public virtual LOJAS_REDE LOJAS_REDE { get; set; }
        public virtual FORNECEDORES FORNECEDORES { get; set; }
    }
}
