//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROP_LOJAS_VAREJO
    {
        public string PROPRIEDADE { get; set; }
        public short ITEM_PROPRIEDADE { get; set; }
        public string VALOR_PROPRIEDADE { get; set; }
        public Nullable<System.DateTime> DATA_PARA_TRANSFERENCIA { get; set; }
        public string CODIGO_FILIAL { get; set; }
    
        public virtual PROPRIEDADE PROPRIEDADE1 { get; set; }
    }
}
