//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.ComisionesMH.DataAccessEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Orkidea.ComisionesMH.Entities;
    
    public partial class MHERPEntities : DbContext
    {
        public MHERPEntities()
            : base("name=MHERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINISTRADORAS_CARTAO> ADMINISTRADORAS_CARTAO { get; set; }
        public DbSet<LOJA_FORMAS_PGTO> LOJA_FORMAS_PGTO { get; set; }
        public DbSet<LOJA_VENDA> LOJA_VENDA { get; set; }
        public DbSet<LOJA_VENDA_PARCELAS> LOJA_VENDA_PARCELAS { get; set; }
        public DbSet<LOJA_VENDA_PGTO> LOJA_VENDA_PGTO { get; set; }
        public DbSet<LOJA_VENDEDORES> LOJA_VENDEDORES { get; set; }
        public DbSet<PROP_LOJAS_VAREJO> PROP_LOJAS_VAREJO { get; set; }
        public DbSet<PROPRIEDADE> PROPRIEDADEs { get; set; }
        public DbSet<TIPOS_PGTO> TIPOS_PGTO { get; set; }
        public DbSet<LOJA_VENDA_PRODUTO> LOJA_VENDA_PRODUTO { get; set; }
        public DbSet<FILIAIS> FILIAIS { get; set; }
        public DbSet<CADASTRO_CLI_FOR> CADASTRO_CLI_FOR { get; set; }
        public DbSet<PRODUTOS> PRODUTOS { get; set; }
        public DbSet<LOJAS_REDE> LOJAS_REDE { get; set; }
        public DbSet<CSS_PRESUPUESTO_TIENDAS> CSS_PRESUPUESTO_TIENDAS { get; set; }
        public DbSet<FORNECEDORES> FORNECEDORES { get; set; }
        public DbSet<CSS_PARAMETRO_TIENDA> CSS_PARAMETRO_TIENDA { get; set; }
        public DbSet<CSS_PARAMETRO_VENDEDOR> CSS_PARAMETRO_VENDEDOR { get; set; }
    }
}
