//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.MH.WebMiddle.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSS_MENU_MIDDLE
    {
        public string padre { get; set; }
        public string hijo { get; set; }
        public string texto { get; set; }
        public string comando { get; set; }
        public string icono { get; set; }
    }
}
