
/****** Object:  Table [dbo].[CSS_PARAMETRO_VENDEDOR]    Script Date: 01/21/2014 16:57:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CSS_PARAMETRO_VENDEDOR](
	[vendedor] [char](4) NOT NULL,
	[comisionCumple] [decimal](14, 2) NOT NULL,
	[comisionNoCumple] [decimal](14, 2) NOT NULL,
 CONSTRAINT [PK_CSS_PARAMETRO_VENDEDOR] PRIMARY KEY CLUSTERED 
(
	[vendedor] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


